# Generated by Django 2.0.7 on 2018-08-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_pp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Service Delivery', 'verbose_name_plural': 'Services Deliveries'},
        ),
    ]
