# Generated by Django 2.0.7 on 2018-10-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_pp', '0004_set_extras_default_value_to_callable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='services',
            field=models.ManyToManyField(related_name='deliveries', to='hivs_pp.Service', verbose_name='services provided'),
        ),
    ]
