# Generated by Django 2.0.7 on 2018-10-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_pp', '0005_change_delivery_services_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='referral_made',
            field=models.BooleanField(default=False, verbose_name='referral was issued'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='referral_successful',
            field=models.BooleanField(default=False, verbose_name='referral was succesful'),
        ),
    ]
