# Generated by Django 2.0.7 on 2018-10-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_pp', '0006_add_referral_made_and_successful_to_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Service Delived', 'verbose_name_plural': 'Services Delivered'},
        ),
    ]
