# Generated by Django 2.0.7 on 2018-10-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_pp', '0007_change_verbose_name_on_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='confidential',
            field=models.BooleanField(default=False, verbose_name='is confidential'),
        ),
    ]
