# Generated by Django 2.0.7 on 2018-10-25 16:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_utils', '0004_create_model_occupation'),
        ('hivs_pp', '0009_allow_blank_client_field_on_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='age',
            field=models.IntegerField(blank=True, help_text="If client profile is set this can be overwritten based on the client's birthdate.", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='client age'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='gender',
            field=models.ForeignKey(help_text="If client profile is set this can be overwritten based on the client's profile.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_deliveries', to='hivs_utils.Gender', verbose_name='client gender'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Do not fill this field is some of the provided services are confidential.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_deliveries', to='hivs_clients.Profile', verbose_name='client profile'),
        ),
    ]
