# Generated by Django 2.0.7 on 2018-10-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_pp', '0010_add_gender_and_age_fields_on_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='confidential',
            new_name='is_confidential',
        ),
    ]
