# Generated by Django 2.0.7 on 2018-10-25 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_pp', '0011_rename_field_confidential_to_is_confidential_on_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='gender',
            field=models.ForeignKey(blank=True, help_text="If client profile is set this can be overwritten based on the client's profile.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_deliveries', to='hivs_utils.Gender', verbose_name='client gender'),
        ),
    ]
