# Generated by Django 2.0.7 on 2018-10-25 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_pp', '0012_allow_blank_gender_field_on_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_delivery_providers', to=settings.AUTH_USER_MODEL, verbose_name='service provider'),
        ),
    ]
