# Generated by Django 2.0.7 on 2018-10-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_pp', '0013_allow_blank_provider_field_on_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='select if this service delivery information should not be linked with clients profiles', verbose_name='is confidential'),
        ),
    ]
