# Generated by Django 2.0.7 on 2018-10-29 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_administrative', '0008_add_areatype'),
        ('hivs_pp', '0014_add_help_text_on_service_is_confidential_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_deliveries', to='hivs_administrative.Area', verbose_name='area'),
        ),
    ]
