# Generated by Django 2.0.7 on 2018-10-29 13:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_pp', '0016_add_field_related_areas_to_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='related_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, editable=False, null=True, size=None, verbose_name='related areas'),
        ),
    ]
