# Generated by Django 2.0.7 on 2018-10-29 14:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_pp', '0017_change_field_related_areas_on_delivery_to_charfield_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='related_areas_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, editable=False, null=True, size=None, verbose_name='related areas ids'),
        ),
    ]
