# Generated by Django 2.0.7 on 2018-08-01 19:32

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='number')),
                ('first_name', models.CharField(max_length=255, verbose_name='name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last_name')),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('gender', models.CharField(max_length=25, verbose_name='gender')),
                ('martial_status', models.CharField(max_length=25, verbose_name='martial status')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('other_phones', django.contrib.postgres.fields.ArrayField(base_field=phonenumber_field.modelfields.PhoneNumberField(max_length=128), blank=True, default=[], size=None)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('education_level', models.CharField(blank=True, max_length=255, verbose_name='education level')),
                ('occupation', models.CharField(blank=True, max_length=255, verbose_name='occupation')),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Geolocation')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='extras')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'abstract': False,
            },
        ),
    ]
