# Generated by Django 2.0.7 on 2018-08-02 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_administrative', '0002_create_model_street'),
        ('hivs_clients', '0002_alter_verbose_names_on_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_profiles', to='hivs_administrative.Area', verbose_name='administrative area'),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_profiles', to='hivs_administrative.Street', verbose_name='street'),
        ),
    ]
