# Generated by Django 2.0.7 on 2018-08-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_clients', '0003_add_field_street_and_area_to_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='number',
            new_name='registration_id',
        ),
    ]
