# Generated by Django 2.0.7 on 2018-08-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_clients', '0004_rename_field_number_to_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='registration number'),
        ),
    ]
