# Generated by Django 2.0.7 on 2018-09-19 12:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_clients', '0005_change_client_registration_id_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extras'),
        ),
    ]
