# Generated by Django 2.0.7 on 2018-10-05 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_clients', '0008_use_callable_list_as_default_other_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acquisition_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True, verbose_name='acquisition date'),
        ),
    ]
