# Generated by Django 2.0.7 on 2018-10-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_clients', '0011_change_acquisition_date_field_to_datefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
    ]
