# Generated by Django 2.0.7 on 2018-10-16 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_utils', '0004_create_model_occupation'),
        ('hivs_clients', '0012_remove_education_level_and_occupation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_profiles', to='hivs_utils.EducationLevel', verbose_name='education level'),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_profiles', to='hivs_utils.Occupation', verbose_name='occupation'),
        ),
    ]
