# Generated by Django 2.1.3 on 2018-11-23 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_clients', '0017_fix_typo_rename_field_martial_status_to_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_profiles', to='hivs_utils.MaritalStatus', verbose_name='marital status'),
        ),
    ]
