# Generated by Django 2.0.7 on 2018-10-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'verbose_name': 'Condom Distribution Center', 'verbose_name_plural': 'Condom Distribution Centers'},
        ),
    ]
