# Generated by Django 2.0.7 on 2018-10-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0002_change_distribution_center_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condomdistribution',
            name='referral_given',
            field=models.BooleanField(default=False, verbose_name='referral was given'),
        ),
    ]
