# Generated by Django 2.0.7 on 2018-10-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0003_correct_referral_given_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condomdistribution',
            name='attendance_type',
        ),
    ]
