# Generated by Django 2.0.7 on 2018-10-24 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_utils', '0004_create_model_occupation'),
        ('hivs_cd', '0004_remove_field_attendance_type_from_condom_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='condomdistribution',
            name='attendance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condom_distributions', to='hivs_utils.AttendanceType', verbose_name='attendance type'),
        ),
    ]
