# Generated by Django 2.0.7 on 2018-10-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0006_update_field_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condomdistribution',
            name='gender',
        ),
    ]
