# Generated by Django 2.0.7 on 2018-10-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_utils', '0004_create_model_occupation'),
        ('hivs_cd', '0007_remove_condomdistribution_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='condomdistribution',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condom_distributions', to='hivs_utils.Gender', verbose_name='client gender'),
        ),
    ]
