# Generated by Django 2.0.7 on 2018-10-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0009_add_model_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purpose',
            options={'verbose_name': 'Condom Distribution Purpose', 'verbose_name_plural': 'Condom Distribution Purposes'},
        ),
    ]
