# Generated by Django 2.0.7 on 2018-10-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0010_change_purpose_model_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='condomdistribution',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condom_distributions', to='hivs_cd.Purpose', verbose_name='purpose'),
        ),
    ]
