# Generated by Django 2.0.7 on 2018-10-25 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0011_add_field_condomdistribution_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condomdistribution',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condom_distributions', to='hivs_cd.Center', verbose_name='distribution center'),
        ),
    ]
