# Generated by Django 2.0.7 on 2018-11-08 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_clients', '0013_add_education_level_and_occupation_fields'),
        ('hivs_cd', '0012_change_related_name_condomdistribution_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='condomdistribution',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condom_distributions', to='hivs_clients.Profile', verbose_name='client profile'),
        ),
        migrations.AddField(
            model_name='condomdistribution',
            name='distributor_contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='distributor contact'),
        ),
        migrations.AddField(
            model_name='condomdistribution',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='client first name'),
        ),
        migrations.AddField(
            model_name='condomdistribution',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='client surname'),
        ),
        migrations.AddField(
            model_name='condomdistribution',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='client middle name'),
        ),
    ]
