# Generated by Django 2.0.7 on 2018-11-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0013_add_fields_to_condomdistribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condomdistribution',
            name='referral_given_type',
        ),
    ]
