# Generated by Django 2.0.7 on 2018-11-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0015_condomdistribution_referral_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condomdistribution',
            name='hiv_education_topics',
        ),
    ]
