# Generated by Django 2.0.7 on 2018-11-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0016_remove_condomdistribution_hiv_education_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condomdistribution',
            old_name='hiv_education_delivered',
            new_name='education_delivered',
        ),
    ]
