# Generated by Django 2.0.7 on 2018-11-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0017_rename_field_education_delivered_on_condomdistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condomdistribution',
            name='education_delivered',
            field=models.BooleanField(default=False, verbose_name='Education was delivered'),
        ),
    ]
