# Generated by Django 2.0.7 on 2018-11-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_utils', '0005_topic'),
        ('hivs_cd', '0018_change_verbose_name_for_education_delivered_on_condomdistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='condomdistribution',
            name='education_topics',
            field=models.ManyToManyField(related_name='condom_distributions', to='hivs_utils.Topic', verbose_name='Education topics delivered'),
        ),
    ]
