# Generated by Django 2.0.7 on 2018-11-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0019_condomdistribution_education_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condomdistribution',
            old_name='referral_given',
            new_name='referral_made',
        ),
    ]
