# Generated by Django 2.0.7 on 2018-11-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0020_rename_referral_give_to_referral_made_on_condom_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='condomdistribution',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='remarks'),
        ),
    ]
