# Generated by Django 2.0.7 on 2018-11-09 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0021_condomdistribution_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condomdistribution',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='condomdistribution',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='condomdistribution',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='center',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='location description'),
        ),
        migrations.AlterField(
            model_name='condomdistribution',
            name='age',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='client age'),
        ),
        migrations.AlterField(
            model_name='condomdistribution',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condom_distributions', to='hivs_utils.Gender', verbose_name='client gender'),
        ),
    ]
