# Generated by Django 2.1.3 on 2018-11-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0022_fields_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condomdistribution',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condom_distributions', to='hivs_cd.Purpose', verbose_name='purpose'),
        ),
    ]
