# Generated by Django 2.1.3 on 2018-11-23 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0023_make_purpose_optional_on_condomdistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condomdistribution',
            name='condoms_female_count',
            field=models.IntegerField(blank=True, default=0, help_text='No. of male condoms delivered', validators=[django.core.validators.MinValueValidator(0)], verbose_name='No. of female condoms provided'),
        ),
        migrations.AlterField(
            model_name='condomdistribution',
            name='condoms_male_count',
            field=models.IntegerField(blank=True, default=0, help_text='No. of male condoms delivered', validators=[django.core.validators.MinValueValidator(0)], verbose_name='No. of male condoms provided'),
        ),
    ]
