# Generated by Django 2.1.3 on 2018-11-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_cd', '0024_allow_blank_values_for_condom_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condomdistribution',
            name='education_topics',
            field=models.ManyToManyField(blank=True, related_name='condom_distributions', to='hivs_utils.Topic', verbose_name='Education topics delivered'),
        ),
    ]
