# Generated by Django 2.0.7 on 2018-09-18 13:35

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hivs_administrative', '0004_add_field_population_source_on_area_and_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('counselor_name', models.CharField(max_length=255, verbose_name='councelor name')),
                ('client_no', models.CharField(max_length=255, verbose_name='client number')),
                ('client_spouce_no', models.CharField(max_length=255, verbose_name='client spouce number')),
                ('attendance_type', models.CharField(max_length=255, verbose_name='attendance type')),
                ('gender', models.CharField(max_length=25, verbose_name='gender')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='age')),
                ('martial_status', models.CharField(max_length=25, verbose_name='martial status')),
                ('pregnancy_status', models.CharField(max_length=25, verbose_name='pregnancy status')),
                ('referrer', models.CharField(blank=True, max_length=255, verbose_name='referrer')),
                ('councelling_type', models.CharField(max_length=255, verbose_name='councelling type')),
                ('agreed_to_test', models.BooleanField(default=False, verbose_name='agreed to test')),
                ('councelled_after_test', models.BooleanField(default=False, verbose_name='councelled after test')),
                ('test_result', models.CharField(blank=True, max_length=25, verbose_name='test result')),
                ('test_result_share', models.CharField(blank=True, help_text='people who test results should be shared with', max_length=25, verbose_name='result sharing')),
                ('tb_tested', models.BooleanField(default=False, verbose_name='tested for TB')),
                ('tb_test_result', models.CharField(blank=True, max_length=25, verbose_name='result for TB test')),
                ('referred_to', models.CharField(blank=True, max_length=255, verbose_name='referred to')),
                ('given_condoms', models.BooleanField(default=False, verbose_name='given condoms')),
                ('remarks', models.TextField(blank=True, verbose_name='remarks')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='extras')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='htc_registers', to='hivs_administrative.Area', verbose_name='administrative area')),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Register',
                'abstract': False,
            },
        ),
    ]
