# Generated by Django 2.0.7 on 2018-09-18 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='area',
            field=models.ForeignKey(help_text='administrative area where the client is comming from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='htc_registers', to='hivs_administrative.Area', verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='register',
            name='given_condoms',
            field=models.BooleanField(default=False, verbose_name='received condom(s)'),
        ),
    ]
