# Generated by Django 2.0.7 on 2018-09-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0002_alter_area_and_given_condoms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='given_condoms',
            new_name='received_condoms',
        ),
    ]
