# Generated by Django 2.0.7 on 2018-09-19 09:02

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_administrative', '0004_add_field_population_source_on_area_and_street'),
        ('hivs_htc', '0003_rename_given_to_received_condoms_on_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('client_no', models.CharField(max_length=255, verbose_name='client number')),
                ('gender', models.CharField(max_length=25, verbose_name='gender')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='age')),
                ('martial_status', models.CharField(max_length=25, verbose_name='martial status')),
                ('occupation', models.CharField(max_length=255, verbose_name='occupation')),
                ('reason', models.CharField(max_length=255, verbose_name='reason')),
                ('services_given', models.TextField(verbose_name='services given')),
                ('unique_info', models.TextField(blank=True, help_text='Example; allergy', verbose_name='services given')),
                ('issuer_name', models.CharField(blank=True, help_text='name of a person who issued the referral', max_length=255, verbose_name='Issuer name')),
                ('issuer_designation', models.CharField(blank=True, help_text='designation of a person who issued the referral', max_length=255, verbose_name='Issuer name')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_type', models.CharField(max_length=255, verbose_name='center type')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='geolocation')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='extras')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_centers', to='hivs_administrative.Area', verbose_name='administrative area')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_centers', to='hivs_administrative.Street', verbose_name='street')),
            ],
            options={
                'verbose_name': 'Referral Center',
                'verbose_name_plural': 'Referral Centers',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='htc_referrals', to='hivs_htc.ReferralCenter', verbose_name='referral center'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='htc_referrers', to='hivs_htc.ReferralCenter', verbose_name='referrer center'),
        ),
    ]
