# Generated by Django 2.0.7 on 2018-09-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0004_add_referral_and_referralcenter_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='age',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='client_no',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='martial_status',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='register',
            name='referred_to',
        ),
        migrations.AddField(
            model_name='referral',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='hivs_htc.Register', verbose_name='referral center'),
        ),
        migrations.AddField(
            model_name='register',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, verbose_name='occupation'),
        ),
    ]
