# Generated by Django 2.0.7 on 2018-09-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0006_alter_unique_info_field_label_on_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referrer_center',
            field=models.ForeignKey(blank=True, help_text='center that issues the referral', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='htc_referrers', to='hivs_htc.ReferralCenter', verbose_name='referrer center'),
        ),
    ]
