# Generated by Django 2.0.7 on 2018-09-19 12:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0007_add_help_text_on_referral_referrer_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcenter',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extras'),
        ),
        migrations.AlterField(
            model_name='register',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extras'),
        ),
    ]
