# Generated by Django 2.0.7 on 2018-09-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0008_set_extras_default_value_to_callable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCenterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='center type')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
            ],
            options={
                'verbose_name': 'Referral Center Type',
                'verbose_name_plural': 'Referral Center Types',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='referralcenter',
            name='center_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='htc_referral_centers', to='hivs_htc.ReferralCenterType', verbose_name='center type'),
        ),
        migrations.AlterField(
            model_name='register',
            name='attendance_type',
            field=models.CharField(choices=[('MP', 'New client'), ('HM', 'Repeating client')], max_length=255, verbose_name='attendance type'),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('ME', 'Male'), ('KE', 'Female')], max_length=25, verbose_name='gender'),
        ),
    ]
