# Generated by Django 2.0.7 on 2018-09-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0009_add_referral_center_type_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcentertype',
            name='code',
            field=models.CharField(blank=True, max_length=25, verbose_name='code'),
        ),
    ]
