# Generated by Django 2.0.7 on 2018-09-19 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0010_alter_field_code_on_referralcentertype_remove_unique_contrain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='referrer',
        ),
        migrations.AddField(
            model_name='register',
            name='referrer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='htc_referrer_registers', to='hivs_htc.ReferralCenterType', verbose_name='referrer'),
        ),
    ]
