# Generated by Django 2.0.7 on 2018-10-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0012_alter_field_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='hivs_htc.Register', verbose_name='register'),
        ),
    ]
