# Generated by Django 2.0.7 on 2018-10-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0013_correct_register_field_verbose_name_on_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='issuer_designation',
            field=models.CharField(blank=True, help_text='designation of a person who issued the referral', max_length=255, verbose_name='issuer designation'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='issuer_name',
            field=models.CharField(blank=True, help_text='name of a person who issued the referral', max_length=255, verbose_name='issuer name'),
        ),
    ]
