# Generated by Django 2.0.7 on 2018-10-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0015_alter_field_verbose_names_on_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='occupation',
        ),
    ]
