# Generated by Django 2.0.7 on 2018-10-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_utils', '0004_create_model_occupation'),
        ('hivs_htc', '0016_remove_register_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='htc_registers', to='hivs_utils.Occupation', verbose_name='occupation'),
        ),
    ]
