# Generated by Django 2.0.7 on 2018-11-11 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0017_add_register_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='tb_tested',
            new_name='tb_screened',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='tb_test_result',
            new_name='tb_screening_result',
        ),
        migrations.RemoveField(
            model_name='register',
            name='occupation',
        ),
        migrations.AlterField(
            model_name='register',
            name='client_spouce_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='client spouce number'),
        ),
        migrations.AlterField(
            model_name='register',
            name='referrer_type',
            field=models.ForeignKey(help_text='Where the client is coming from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='htc_referrer_registers', to='hivs_htc.ReferralCenterType', verbose_name='referred from'),
        ),
        migrations.AlterField(
            model_name='register',
            name='test_result_share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='htc_register_results', to='hivs_utils.ResultSharingChoice', verbose_name='result sharing'),
        ),
    ]
