# Generated by Django 2.0.7 on 2018-11-11 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0018_update_register_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='tb_screened',
            field=models.BooleanField(default=False, verbose_name='screened for TB'),
        ),
        migrations.AlterField(
            model_name='register',
            name='tb_screening_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='htc_register_screening', to='hivs_utils.TBStatus', verbose_name='TB screening result'),
        ),
    ]
