# Generated by Django 2.0.7 on 2018-11-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0019_update_tb_screening_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='councelling_type',
        ),
    ]
