# Generated by Django 2.0.7 on 2018-11-11 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_utils', '0006_councellingtype'),
        ('hivs_htc', '0020_remove_register_councelling_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='councelling_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='htc_registers', to='hivs_utils.CouncellingType', verbose_name='councelling type'),
        ),
    ]
