# Generated by Django 2.0.7 on 2018-11-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0021_register_councelling_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'HTC Register', 'verbose_name_plural': ' HTC Registers'},
        ),
    ]
