# Generated by Django 2.0.7 on 2018-11-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0022_change_register_verbose_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralcentertype',
            options={'verbose_name': 'Referral Type', 'verbose_name_plural': 'Referral Types'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'HTC Register', 'verbose_name_plural': 'HTC Registers'},
        ),
    ]
