# Generated by Django 2.0.7 on 2018-11-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0023_update_model_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='hivs_htc.Register', verbose_name='Client registered as'),
        ),
    ]
