# Generated by Django 2.0.7 on 2018-11-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0025_allow blank TB screening result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='councelling_type',
            new_name='counselling_type',
        ),
    ]
