# Generated by Django 2.0.7 on 2018-11-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0027_fix_typo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='councelled_after_test',
            new_name='counselled_after_test',
        ),
    ]
