# Generated by Django 2.0.7 on 2018-11-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0029_fix_typo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralcentertype',
            options={'verbose_name': 'Referral Center Type', 'verbose_name_plural': 'Referral Center Types'},
        ),
    ]
