# Generated by Django 2.0.7 on 2018-11-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0030_change_referralcentertype_verbose_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'HTC Register', 'verbose_name_plural': 'HTC Register'},
        ),
    ]
