# Generated by Django 2.1.3 on 2018-11-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0031_change_register_vebose_name_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='martial_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='htc_registers', to='hivs_utils.MartialStatus', verbose_name='marital status'),
        ),
    ]
