# Generated by Django 2.1.3 on 2018-11-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0032_fix_marital_status_typo_verbose_name'),
        ('hivs_utils', '0010_fix_typo_rename_model_martialstatus_to_maritalstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='martial_status',
            new_name='marital_status',
        ),
    ]
