# Generated by Django 2.0.7 on 2018-11-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_utils', '0005_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncellingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=25, verbose_name='code')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
            ],
            options={
                'verbose_name': 'Councelling type',
                'verbose_name_plural': 'Councelling types',
            },
        ),
    ]
