# Generated by Django 2.0.7 on 2018-11-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_htc', '0025_allow blank TB screening result'),
        ('hivs_utils', '0006_councellingtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouncellingType',
            new_name='CounsellingType',
        ),
    ]
