# Generated by Django 2.1.3 on 2018-11-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_utils', '0008_change_counsellingtype_verbose_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='martialstatus',
            options={'verbose_name': 'Marital status', 'verbose_name_plural': 'Marital status'},
        ),
    ]
