# Generated by Django 2.1.3 on 2018-11-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_clients', '0016_fix_marital_status_typo_verbose_name'),
        ('hivs_htc', '0032_fix_marital_status_typo_verbose_name'),
        ('hivs_utils', '0009_fix_marital_status_typo_verbose_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MartialStatus',
            new_name='MaritalStatus',
        ),
    ]
