# Generated by Django 2.0.7 on 2018-08-02 08:23

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='code')),
                ('location_description_auto', models.CharField(blank=True, help_text='can be generated automatically', max_length=255, verbose_name='location description')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='population')),
                ('population_male', models.PositiveIntegerField(blank=True, null=True, verbose_name='male population')),
                ('population_female', models.PositiveIntegerField(blank=True, null=True, verbose_name='female population')),
                ('households', models.PositiveIntegerField(blank=True, null=True, verbose_name='number of households')),
                ('population_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='population year')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='Geometry')),
                ('area', models.FloatField(blank=True, help_text='square Meters', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='area')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='Extras')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hivs_administrative.Area', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'abstract': False,
            },
        ),
    ]
