# Generated by Django 2.0.7 on 2018-08-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivs_administrative', '0003_alter_area_field_on_street_set_area_null_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='population_source',
            field=models.CharField(blank=True, max_length=255, verbose_name='population source'),
        ),
        migrations.AddField(
            model_name='street',
            name='population_source',
            field=models.CharField(blank=True, max_length=255, verbose_name='population source'),
        ),
    ]
